config/routes.rb
UspLostAndFound::Application.routes.draw do
  
  authenticated :user do
    root :to => 'home#index'
  end
  
  root :to => "home#index"
  devise_for :users
  resources :users do 
    collection do
      get 'show'
      get 'index'
    end
  end
  
  match "messages/mark_as_read/:item_id", :controller => :messages, :action => 'mark_as_read', :via => :get
  match "replies/mark_as_read/:message_id", :controller => :replies, :action => 'mark_as_read', :via => :get
  
  
  resources :messages
  resources :replies  
  
  resources :items do
    collection do
      get 'new_lost'
      get 'new_found'
      get 'search'
      get 'recover'
      get 'autocomplete_tag_name'
      get 'tag'
      get 'recovered'
    end
  end
   
  get 'tags/:tag', :to => 'items#tag', :as => :tag 
  
  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
  match 'sobre' => 'contact#about', :as => 'about', :via => :get
end

ActionDispatch::Routing::Translator.translate_from_file(
  'config/locales/routes.yml', {
    prefix_on_default_locale: false,
    keep_untranslated_routes: true })
 

app/models/user.rb
class User < ActiveRecord::Base
	rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :avatar
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "image_not_found_:style.jpg"
  
  
  has_many :items
  has_many :sent_messages, :class_name => Message, :foreign_key => 'sender_id'
  has_many :received_messages, :class_name => Message, :foreign_key => 'recipient_id'
  
  has_many :replies, :class_name => Reply
  
  validates :name, :presence => true
  
  def all_messages
    aux = sent_messages
    aux = aux + received_messages
    aux
  end
  
  def unread_messages    
    received_messages.select{|m| m.unread?}
  end
  
  def unread_replies    
    unread = []
    for message in all_messages
      unread.concat message.replies.select{|r| (r.user != self) && r.unread? }
    end
    unread
  end
  
  def all_unread_count
    unread_messages.count + unread_replies.count
  end
  
  def name_with_message_count
    if self.all_unread_count() == 0
      name
    else
      name + " (#{self.all_unread_count()})"
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user! 
  
  load_and_authorize_resource
  
  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @items = @user.items.order("created_at desc")
    @messages = current_user.all_messages
    
    @others_items = []
    
    @user.sent_messages.each do |message|
      @others_items << message.item unless @others_items.include? message.item
    end
    
    respond_to do |format|
      format.js
      format.html
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_item_info.html.erb
<div class="row item-data; padding: 10px">
	<%  if @item.returned %>
		<p style="color: green; text-align: center;"><%= @item.lost? ? "Item recuperado" : "Item 	devolvido" %>
		</p>
	<% end %>
	
	<div class="three columns" style="margin: 10px 0px 10px 10px">
			<%= link_to image_tag(@item.main_image_medium), @item.main_image %>
	</div>
	
	<div class="eight columns end">
		<div class="six columns">
			<p class="sub title"><%= link_to @item.title, item_path(@item) %></p>
		
			<p><%= @item.description%></p>
		</div>
			
		<div class="six columns end">	
			<p>Data em que o item foi <%= @item.lost? ? "perdido: " : "encontrado: "%><br />
			<%=l @item.lost_date %></p>
		
			<% if @item.lost? %>
				<p>Recompensa: <br/> <%= @item.reward %></p>
			<%end%>
			
			<p>Tags: <br/> <%= raw @item.tag_list.map {|t| link_to(t, tag_path(t))}.join(', ') %></p>
			
			<% if can? :edit, @item%>
				<%= link_to 'Editar', edit_item_path(@item), :class=>"small button"%>
				<%= link_to (@item.lost? ? 'Recuperado' : "Devolvido"), recover_items_path(:id => @item.id), :class=>"small button" unless @item.returned %>
			<% end %>
		</div>
	</div>
</div>

<div class="row" style="padding: 10px">
	<%= render 'messages/show_messages' %>
</div>

app/views/users/index.html.erb
<div class="row" style="margin-bottom:30px">
	<span class="title">Usuários</span>
	<hr class="separador"/>
</div>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %> registrado em: <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<script>
	items = [];
</script>
<div class="row" style="margin-bottom: 20px">
	<div class="three columns">
		<%= image_tag(@user.avatar.url(:thumb)) %>
	</div>
	<div class="eight columns end">
		<h3><%= @user.name %></h3>
	</div>
</div>


<div class="row" style="margin-bottom:30px">
	<span class="title user">MEUS ITENS</span>
	<hr class="separador user"/>
</div>

<% if @items.empty? %>
	<div class="sub title user center">Não há itens</div>
<%else%>
	<div class="row user sub title table-header">

		<div class="two columns">
			TÍTULO
		</div>

		<div class="three columns">
			DESCRIÇÃO
		</div>

		<div class="two columns">
			DATA
		</div>
		
		<div class="three columns">
			NOVAS MENSAGENS
		</div>

		<div class="two columns">
			RECOMPENSA
		</div>

		<hr class="separador user"/>
	</div>

		<% @items.each_with_index do |item, i| %>
		<% @item = item; @messages = @item.messages.order("created_at DESC") %>
		<div class="row tags table <%= 'impar' if i%(2) == 0 %>" id="item-<%= item.id %>" style="cursor: pointer; border-color:#D94;">

			<div class="two columns text">
				<span class ="user <%item.lost? ? 'lost' : 'found'%>">
					<%= item.title %>
				</span>
			</div>

			<div class="three columns text">
				<%= item.description %>
			</div>

			<div class="two columns text">
				<%= item.show_date %>
			</div>
			
			<div class="three columns center text">
				<%= item.all_unread_presentation(current_user) %>
			</div>

			<div class="two columns text">
				<%= item.reward %>
			</div>
			
		</div>
	
		<div class="row" id="informacoes-<%= item.id%>" style="border-color:#D94; display:none">		
			<%= render 'item_info'%>
		</div>
	
		<script>
		$(document).ready(function() {
		 	items.push(<%=@item.id %>);
		});
		</script>
	<% end %>
<% end %>

<div class="row" style="margin-bottom:30px; margin-top: 30px">
	<span class="title other">ITENS QUE MANDEI MENSAGEM</span>
	<hr class="separador other"/>
</div>

<% if @others_items.empty? %>
	<div class="sub title other center">Não há itens</div>
<%else%>

	<div class="row other sub title table-header">

		<div class="two columns">
			TÍTULO
		</div>

		<div class="three columns">
			DESCRIÇÃO
		</div>

		<div class="two columns">
			DATA
		</div>
		
		<div class="three columns">
			NOVAS MENSAGENS
		</div>

		<div class="two columns">
			RECOMPENSA
		</div>

		<hr class="separador other"/>
	</div>

		<% @others_items.each_with_index do |item, i| %>
			<% @item = item; @messages = @item.user_messages(@user) %>

			<div class="row tags table <%= 'impar' if i%(2) == 0 %>" id="item-<%= item.id %>" style="cursor: pointer; border-color:#964;">


				<div class="two columns text">
					<span class ="user <%item.lost? ? 'lost' : 'found'%>">
						<%= item.title %>
					</span>
				</div>

				<div class="three columns text">
					<%= item.description %>
				</div>

				<div class="two columns text">
					<%= item.show_date %>
				</div>
				
				<div class="three columns center text">
					<%= item.all_unread_presentation(current_user) %>
				</div>

				<div class="two columns text">
					<%= item.reward %>
				</div>
			</div>
	
			<div class="row" id="informacoes-<%= item.id%>" style="border-color:#964; display:none">		
				<%= render 'item_info'%>
			</div>
	
			<script>
				$(document).ready(function() {
			 		items.push(<%=@item.id %>);
				});
			</script>
		<% end %>
<% end %>

<script>
	$(document).ready(function() {
		
		for (i in items) {
			console.log($("#item-" + items[i]))
			$("#item-" + items[i]).click(function() {
				_id = (this.id.split('-')[1]);
				$.ajax({
					url: "/messages/mark_as_read/" + _id
				})
				$("#informacoes-" + _id).toggle(0.1, function() {
					
					_id = (this.id.split('-')[1]);
					if(this.style.display != 'none') {
						$('#item-' + _id).css("border-style", "solid");
						$('#item-' + _id).css("border-width", "2px 2px 0px 2px ");
						$('#informacoes-' + _id).css("border-style", "solid");
						$('#informacoes-' + _id).css("border-width", "0px 2px 2px 2px ");
					}
					
					else {
							$('#item-' + _id).css("border-style", "none");
							$('#informacoes-' + _id).css("border-style", "none");
					}
					
				});
			});
		}
	});
</script>

<script>
	$(document).ready(function() {
	 	window.registerClick(contents);
		
		for (i in contents) {
			$("#message-" + contents[i]).click(function() {
				_id = (this.id.split('-')[1]);
				$.ajax({
					url: "/replies/mark_as_read/" + _id
				})
				$("#respostas-" + _id).toggle();
			});
		}
	});
</script>