config/routes.rb
UspLostAndFound::Application.routes.draw do
  
  authenticated :user do
    root :to => 'home#index'
  end
  
  root :to => "home#index"
  devise_for :users
  resources :users do 
    collection do
      get 'show'
      get 'index'
    end
  end
  
  match "messages/mark_as_read/:item_id", :controller => :messages, :action => 'mark_as_read', :via => :get
  match "replies/mark_as_read/:message_id", :controller => :replies, :action => 'mark_as_read', :via => :get
  
  
  resources :messages
  resources :replies  
  
  resources :items do
    collection do
      get 'new_lost'
      get 'new_found'
      get 'search'
      get 'recover'
      get 'autocomplete_tag_name'
      get 'tag'
      get 'recovered'
    end
  end
   
  get 'tags/:tag', :to => 'items#tag', :as => :tag 
  
  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
  match 'sobre' => 'contact#about', :as => 'about', :via => :get
end

ActionDispatch::Routing::Translator.translate_from_file(
  'config/locales/routes.yml', {
    prefix_on_default_locale: false,
    keep_untranslated_routes: true })
 

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :store_location
  
  def index
    @users = User.all
    @item = Item.new
    @items_lost = Item.where(:lost => true, :returned => false).order("created_at DESC").limit(10)
    @items_found = Item.where(:lost => false, :returned => false).order("created_at DESC").limit(10)
    @tags = Item.tag_counts_on(:tags).order("name")
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="row">
	<div class="six columns">
		<div class="row">
		
			<div class="four column lost title">
				EU PERDI
			</div>
		</div>
		<hr class="separador lost"></hr>
		
		<div class="twelve columns lost box">
			<div class="row">
				<%= simple_form_for(:item, :url => :search_items, :method => :get)  do |f| %>
					<div class="nine columns">
						<%= f.input :search, input_html: {value: '' }, required: false, label: false %>
					</div>
					<%= f.input :lost, :as => :hidden, :input_html => {:value => true}%>

					<div class="three columns right">
						<%= f.submit "Buscar", :class => "secondary small button", :id => "buscar_perdido"  %><br/>
					</div>
				<% end %>
			</div>
			
		<div class="row">
			
			<div class="nine columns">
				Não encontrou seu objeto?
				Cadastre a ocorrência aqui.
			</div>
			
			<div class="three columns right">
				<a class="secondary small button" href="<%=new_lost_items_path%>">Cadastrar</a>
				
			</div>
			<div class="nine columns end">
				<p>Veja os <%= link_to "items recuperados.", recovered_items_path(:lost => true) %></p>
			</div>
		</div>
		
		<div class="row" style="margin-top: 20px">
			<div class="eight columns title lost">
				OBJETO
			</div>
			
			<div class="four columns title lost">		
				DATA
			</div>
		</div>
		<hr class="separador lost"/>
		
		<div class="row">
			<% for item in @items_lost %>
				<p class="eight columns one-line">
					<%= link_to item.title + " - " + item.description, item_path(item)%>
				</p>
				
				<p class="four columns">
					<%=l item.lost_date%>
				</p>
			<% end %>
		</div>
		</div>
	</div>

	<div class="six columns" style="padding:0px 0px 0px 10px">
		
		<div class="row">
		
			<div class="four column found title">
				EU ACHEI
			</div>
		</div>
		
		<hr class="separador found"/>
		
		<div class="twelve columns found box">
		
		<div class="row">
			<%= simple_form_for(:item, :url => :search_items, :method => :get) do |f| %>
				<div class="nine columns">
						<%= f.input :search, input_html: {value: '' }, required: false, label: false %>
				</div>
						<%= f.input :lost, :as => :hidden, :input_html => {:value => false} %>
				<div class="three columns right">
						<%= f.submit "Buscar",  :class => "secondary small button", :id => "buscar_encontrado" %><br/>
				</div>
				<% end %>
		</div>
			
		<div class="row">
			<div class="nine columns">
				Encontrou um objeto e quer devolve-lo?
				Cadastre-o aqui e encontre o dono.
			</div>

			<div class="three columns right">
				<a class="secondary small button" href="<%=new_found_items_path%>">Cadastrar</a>
			</div>
			
			<div class="nine columns end">
				<p>Veja os <%= link_to "items devolvidos.", recovered_items_path(:lost => false) %></p>
			</div>
		</div>
		
		<div class="row" style="margin-top: 20px">
			<div class="eight columns title found">
				OBJETO
			</div>
			
			<div class="four columns title found">		
				DATA
			</div>
		</div>
		
		<hr class="separador found"/>
		
		<div class="row">
			<% for item in @items_found %>
				<p class="eight columns one-line">
					<%= link_to item.title + " - " + item.description, item_path(item)%>
				</p>
				
				<p class="four columns">
					<%=l item.lost_date %>
				</p>
			<% end %>
		</div>
	</div>
	</div>
</div>

<div class="row" id="tag_cloud" style="margin-top:30px; margin-bottom:10px;">
	<div class="two columns">
	</div>
	
	<div class="eight columns" style="min-height: 45px">
  	<% tag_cloud @tags, %w[small medium large] do |tag, css_class| %>
    	<%= link_to tag.name, tag_path(tag.name), class: css_class %>
  	<% end %>
	</div>
	
	<div class="two columns">
	</div>
</div>