config/routes.rb
UspLostAndFound::Application.routes.draw do
  
  authenticated :user do
    root :to => 'home#index'
  end
  
  root :to => "home#index"
  devise_for :users
  resources :users do 
    collection do
      get 'show'
      get 'index'
    end
  end
  
  match "messages/mark_as_read/:item_id", :controller => :messages, :action => 'mark_as_read', :via => :get
  match "replies/mark_as_read/:message_id", :controller => :replies, :action => 'mark_as_read', :via => :get
  
  
  resources :messages
  resources :replies  
  
  resources :items do
    collection do
      get 'new_lost'
      get 'new_found'
      get 'search'
      get 'recover'
      get 'autocomplete_tag_name'
      get 'tag'
      get 'recovered'
    end
  end
   
  get 'tags/:tag', :to => 'items#tag', :as => :tag 
  
  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
  match 'sobre' => 'contact#about', :as => 'about', :via => :get
end

ActionDispatch::Routing::Translator.translate_from_file(
  'config/locales/routes.yml', {
    prefix_on_default_locale: false,
    keep_untranslated_routes: true })
 

app/models/item.rb
# encoding: utf-8
class Item < ActiveRecord::Base
  attr_accessible :assets_attributes, :description, :lost_date, :lost, :returned, :reward, :title, :tag_list
  has_many :assets
  has_many :messages
  belongs_to :user
  validates :user_id, :presence => true
  validates :title, presence: true
  validates :description, :presence => true
  validates_date :lost_date
  validates_date :lost_date, :before => lambda { Date.today + 1.day }, 
    :before_message => "Data inválida"
  
  accepts_nested_attributes_for :assets, :allow_destroy => :true
  
  acts_as_taggable
  
  searchable do
    text :title, :boost => 2.0
    text :description
    boolean :lost
    boolean :returned
    
    text :tag_list do
      tag_list.map {|tag| tag}
    end
  end
    
  def main_image_thumb
    if assets.empty?
     "image_not_found_thumb.jpg"
    else
      assets.first.asset.url(:thumb)
    end
  end
  
  def main_image_medium
    if assets.empty?
     "image_not_found_medium.jpg"
    else
      assets.first.asset.url(:medium)
    end
  end
  
  def main_image
    if assets.empty?
     "javascript:void(0)"
    else
      assets.first.asset.url(:original)
    end
  end
  
  def show_date
    if lost_date.nil?
      Time.now.strftime("%d/%m/%Y")
    else
      lost_date.strftime("%d/%m/%Y")
    end
  end
  
  def user_messages(user)
    _messages = messages.select{|m| m.sender == user}
    _messages.sort {|a, b| b.created_at <=> a.created_at}
  end
  
  def unread_messages(user)
    messages.select{|m| m.recipient == user && m.unread?}
  end
  
  def unread_replies(user)
    unread = []
    messages.select{|m| (m.sender == user) || (m.recipient == user) }.each do |message|
      unread.concat message.replies.select{|r| (r.user != user) && r.unread? }
    end
    
    unread
  end
  
  def all_unread_count(user)
    unread_messages(user).count + unread_replies(user).count
  end
  
  def all_unread_presentation(user)
    count = all_unread_count(user)
    if count == 0
      "Não há novas mensagens"
    else
      count
    end
  end
  
end

app/controllers/items_controller.rb
require 'ItemRecomender'
class ItemsController < ApplicationController
  before_filter :authenticate_user!, :only => [:new_lost, :new_found, :create, :update, :destroy]
  before_filter :store_location
  
  autocomplete :tag, :name, :class_name => 'ActsAsTaggableOn::Tag'

  load_and_authorize_resource
  
  def new_item
    @item = Item.new
    @item.assets.build
  end

  def new_lost
    new_item    
    @item.lost = true
  end
  
  def new_found
    new_item
    @item.lost = false
  end
  
  # GET /items/1
  def show
    @item = Item.find(params[:id])
    @message = Message.new
        
    if @item.user == current_user
      lost = !@item.lost
      @same_user = true
    else
      lost = @item.lost
      @same_user = false
    end
      
    @recomendeds = ItemRecomender.similar(@item, 5, lost)
    
  end

  def edit
    @item = Item.find(params[:id])
    @item.assets.build
  end

  def create
    @item = Item.new(params[:item])
    @item.user = current_user
    @item.returned = false

    if @item.save
      redirect_to @item, notice: 'Item cadastrado com sucesso.'
    else
      @item.assets.build
      render action: @item.lost? ? "new_lost" : "new_found"
    end
  end

  # PUT /items/1
  def update
    @item = Item.find(params[:id])
    
    if @item.update_attributes(params[:item])
      redirect_to @item, notice: 'Item atualizado com sucesso'
    else
      @item.assets.build
      render action: "edit"
    end
  end

  # DELETE /items/1
  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_url
  end
  
  def search
    
    aux = params[:item]
    lost = (aux[:lost] == "true") ? true : false
    termo = aux[:search] 
    
    if termo.blank?   
      @items = Item.where(:lost => lost, :returned => false).sort! {|a, b| b.created_at <=> a.created_at}
    else
      @search = Item.search do
      
        with(:returned, false)      
        with(:lost, lost)
      
        keywords termo, :minimum_match => 1
      end
      @items = @search.results
    end
    
    
    @lost = lost

  end
  
  def tag
    if params[:tag]
      @items = Item.tagged_with(params[:tag]).order('created_at DESC')
    end
  end

  def recover 
    item = Item.find(params[:id])
    item.returned = true
    item.save!
    
    if item.lost?
      returned = "recuperado"
    else
      returned = "devolvido"
    end
    
    redirect_to :back, :notice => "Item marcado como #{returned}"
  end
  
  def recovered
    @lost = params[:lost] == 'true' ? true : false
    @items = Item.where(:returned => true, :lost => @lost)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= simple_form_for(@item, :html => {:multipart => true}) do |f| %>
  <%= f.error_notification %>

	<div class="row">
		<div class="five columns">
			<%= f.input :title, required: true %>
		</div>
		
		<div class="six columns end offset-by-one">
			<div class="three columns">
				<label for="aseets">Imagem</label>
				<% i=0 %>
					<%= f.fields_for :assets do |asset_fields|%>
						<% if asset_fields.object.new_record? %>
							<%if i == 0 %>
								<div class="small file button secondary file" id="files">
									Arquivo
								</div><div id="filename" class="one-line" style="padding-right: 0px"></div>
									<%= asset_fields.file_field(:asset, :style => "width:0; height:0; overflow: hidden;", :id => "file")%>
								<% i += 1%>
							<% end %>
						<%end%>
					<%end%>
			</div>

			<div class="mini-images six columns end">
				<%= f.fields_for :assets do |asset_fields|%>
					<% unless asset_fields.object.new_record? %>
						<div class="three columns">
							<%= link_to image_tag(asset_fields.object.asset.url(:thumb)), asset_fields.object.asset.url(:original)%><br/>
							remover <%= asset_fields.check_box :_destroy%>
						</div>
						<% end %>

				<%end%>
			</div>
			
		</div>
	</div>
	
	<div class="row">
  	<div class="five columns">
			<%= f.input :description, :required => true, as: :text, :input_html => {:columns => 10, :rows => 10}%>
		</div>

	<div class="five columns offset-by-one">
		<%= f.input :lost_date, :required => true, :as => :string, :label => "Data que o item foi " + (@item.lost? ? "perdido" : "encontrado"), :input_html => {:value => @item.show_date } %>
	</div>
		
	<div class="five columns offset-by-one">
		<%= f.input :tag_list, :label => "Tags (separadas por virgula)", :url => autocomplete_tag_name_items_path, :as => :autocomplete, :input_html => {:'data-delimiter' => ', '} %>
	</div>

	<div class="five columns offset-by-one">
		<% if @item.lost? %>
			<%= f.input :reward, :label => "Recompensa" %>
		<% end %>
	</div>		
	
	<div class="five columns offset-by-one">
		<% unless @item.new_record? %>
			<%= f.input :returned, :inline_label => (@item.lost? ? "Recuperado" : "Devolvido"), :label => false%>
		<% end %>
	</div>
	
	<%=f.input :lost, :as => :hidden %>
	
	</div>
	
		
  <div class="row">
    <%= f.button :submit, :class => "button secondary" %>
  </div>

<% end %>

app/views/items/_list_items.html.erb
<ul>
	<% @items.each_with_index do |item, i| %>
	
		<div class="row table item <%= 'impar' if i%(2) == 0 %>">

			<div class="two columns text">
				<%= link_to item.title, item_path(item), :class => "#{item.lost? ? 'lost' : 'found'}" %>
			</div>

			<div class="four columns text">
				<%= item.description %>
			</div>

			<div class="two column image">
				<%= link_to image_tag(item.main_image_thumb), item.main_image %>
			</div>

			<div class="two columns text">
				<%= item.show_date %>
			</div>

			<div class="two columns text">
				<%= item.reward %>
			</div>
		</div>
	<% end %>
</ul>

app/views/items/edit.html.erb
<div class="row ">
	<span class="<%= @item.lost? ? 'lost'  : 'found'  %> title">EDITAR ITEM</span>
	<hr class="separador <%= @item.lost? ? 'lost'  : 'found'  %>"/>
</div>

<div style="margin-top: 10px">
<%= render 'form' %>
</div>

app/views/items/index.html.erb
<h1>Listagem de itens</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
		<td><%= item.title %></td>
		<td><%=l item.lost_date %></td>
    <td><%= link_to 'Mostrar', item %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Cadastrar item perdido', new_lost_items_path %> |
<%= link_to 'Cadastrar item encontrado', new_found_items_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/new_found.html.erb
<div class="row " style="margin-bottom:20px">
	<span class="found title">EU ACHEI</span>
	<hr class="separador found"/>
</div>

<%= render 'form' %>

app/views/items/new_lost.html.erb
<div class="row " style="margin-bottom:20px">
	<span class="lost title">EU PERDI</span>
	<hr class="separador lost"/>
</div>

<%= render 'form' %>

app/views/items/recovered.html.erb
<div class="row" style="margin-bottom: 30px">
	<% if @lost %>
		<span class="lost title">EU PERDI</span>
		<hr class="separador lost"/>
		<span class="lost sub title">SOLUCIONADOS</span>
	<% else %>
		<span class="found title">EU ACHEI</span>
		<hr class="separador found"/>
		<span class="found sub title">SOLUCIONADOS</span>
	<% end %>
</div>

<% if @items.empty? %>
	<div class="row title center">
		Ainda não há itens <%= @lost ? "recuperados" : "devolvidos" %>
	</div>
<% else %>

	<% if @lost %>
		<div class="row lost sub title table-header">
		
			<div class="two columns">
				TÍTULO
			</div>
		
			<div class="four columns">
				DESCRIÇÃO
			</div>
		
			<div class="two column">
				IMAGEM
			</div>
		
			<div class="two columns">
				DATA
			</div>
		
			<div class="two columns">
				RECOMPENSA
			</div>
		
			<hr class="separador lost"/>
		</div>
	<% else %>
	<div class="row found sub title table-header">
	
		<div class="two columns">
			TÍTULO
		</div>
	
		<div class="four columns">
			DESCRIÇÃO
		</div>
	
		<div class="two column">
			IMAGEM
		</div>
	
		<div class="two columns">
			DATA
		</div>
	
		<div class="two columns">
			RECOMPENSA
		</div>
	
		<hr class="separador found"/>
	</div>
	<% end %>
	
	<%= render 'list_items' %>
<% end %>

app/views/items/search.html.erb
<div class="row" style="margin-bottom: 30px">
	<% if @lost %>
		<span class="lost title">EU PERDI</span>
		<hr class="separador lost"/>
		<span class="lost sub title">RESULTADOS</span>
	<% else %>
		<span class="found title">EU ACHEI</span>
		<hr class="separador found"/>
		<span class="found sub title">RESULTADOS</span>
	<% end %>
</div>

<% if @items.empty? %>
	<div class="row title center">
		Não há resultados para essa busca
	</div>
<% else %>

	<% if @lost %>
		<div class="row lost sub title table-header">
		
			<div class="two columns">
				TÍTULO
			</div>
		
			<div class="four columns">
				DESCRIÇÃO
			</div>
		
			<div class="two column">
				IMAGEM
			</div>
		
			<div class="two columns">
				DATA
			</div>
		
			<div class="two columns">
				RECOMPENSA
			</div>
		
			<hr class="separador lost"/>
		</div>
	<% else %>
	<div class="row found sub title table-header">
	
		<div class="two columns">
			TÍTULO
		</div>
	
		<div class="four columns">
			DESCRIÇÃO
		</div>
	
		<div class="two column">
			IMAGEM
		</div>
	
		<div class="two columns">
			DATA
		</div>
	
		<div class="two columns">
			RECOMPENSA
		</div>
	
		<hr class="separador found"/>
	</div>
	<% end %>
	
	<%= render 'list_items' %>
<% end %>

app/views/items/search_found.html.erb
<h3>Resultados da busca</h3>

<ul>
	<% for item in @items %>
		<li><%= link_to item.title, item_path(item) %></li>
	<% end %>
</ul>

app/views/items/show.html.erb
<div class="row" style="margin-bottom: 0px">
	
	<div class="row" style="height: 100px; position: relative">
		<div class="five columns title <%= @item.lost? ? "lost" : "found"%>" style="position: absolute; bottom: 0px">
			<%= @item.user.name %>
		</div>
	
		<div class="two columns end offset-by-eight" style="position: absolute; bottom: 0px">
			<%= image_tag @item.user.avatar.url(:thumb)%> 
		</div>
	</div>
		
	<hr class="separador <%= @item.lost? ? "lost" : "found"%>" />
	
	<div class="two columns end sub title <%= @item.lost? ? "lost" : "found"%>" style="padding-left: 0px; margin-bottom: 20px" >
		<%= @item.lost? ? "Perdeu" : "Encontrou"%>
	</div>
</div>

<%  if @item.returned %>
	<h4 style="color: green; text-align: center;"><%= @item.lost? ? "Item recuperado" : "Item 	devolvido" %>
	</h4>
<% end %>
<div class="row item-data">
	<div class="three columns">
			<%= link_to image_tag(@item.main_image_medium), @item.main_image %>
	</div>
	
	<div class="eight columns end">
		<div class="six columns">
			<p class="sub title"><%= @item.title %></p>
		
			<p><%= @item.description%></p>
		</div>
			
		<div class="six columns end">	
			<p>Data em que o item foi <%= @item.lost? ? "perdido: " : "encontrado: "%><br />
			<%=l @item.lost_date %></p>
		
			<% if @item.lost? %>
				<p>Recompensa: <br/> <%= @item.reward %></p>
			<%end%>
			
			<p>Tags: <br/> <%= raw @item.tag_list.map {|t| link_to(t, tag_path(t))}.join(', ') %></p>
		</div>
	</div>
</div>

<%unless @item.returned? %>
	<% if current_user && (@item.user != current_user) %>
	<div class="row" style="margin-top: 10px">
		<%= render "messages/send_message"%>
	</div>
	<%end%>
<%end%>

<div class="row">
	<%if can? :update, @item%>
		<%= link_to 'Editar', edit_item_path(@item) %>
	<% end%>
	
</div>

<div class="row">
	<div class="six columns offset-by-two center">
		<% unless @recomendeds.empty? %>
			<% if @same_user %>
				<p>Itens <%= @item.lost? ? "encontrados" : "perdidos" %> parecidos com este</p>
			<% else%>
				<p>Itens parecidos com este</p>
			<%end%>

		<% end %>
			<% for recomended in @recomendeds %>
				<div class="five columns center end" style="padding: 10px; margin:10px">
					<%= link_to(item_path(recomended)) do %>
						<span style="max-height:150px">
							<%= image_tag recomended.main_image_thumb, :style=>"max-height: 100px" %>
							<p><%= recomended.title %></p>
						</span>
					<% end %>
				</div>	
			<% end %>
	</div>
</div>

app/views/items/tag.html.erb
<div class="row" style="margin-bottom: 30px">
	<div class="title">TAGS</div>
	<hr class="separador"/>
	<div class="sub title">RESULTADOS</div>
</div>

<% if @items.nil? || @items.empty? %>
	<div class="row title center">
		Não há resultados para essa busca
	</div>
<% else %>

<div class="row sub title table-header">
	
	<div class="two columns">
		TÍTULO
	</div>
	
	<div class="four columns">
		DESCRIÇÃO
	</div>
	
	<div class="two column">
		IMAGEM
	</div>
	
	<div class="two columns">
		DATA
	</div>
	
	<div class="two columns">
		RECOMPENSA
	</div>
	
	<hr class="separador"/>
</div>

<div class="tags">
	<%= render 'list_items' %>
</div>
<% end %>