config/routes.rb
UspLostAndFound::Application.routes.draw do
  
  authenticated :user do
    root :to => 'home#index'
  end
  
  root :to => "home#index"
  devise_for :users
  resources :users do 
    collection do
      get 'show'
      get 'index'
    end
  end
  
  match "messages/mark_as_read/:item_id", :controller => :messages, :action => 'mark_as_read', :via => :get
  match "replies/mark_as_read/:message_id", :controller => :replies, :action => 'mark_as_read', :via => :get
  
  
  resources :messages
  resources :replies  
  
  resources :items do
    collection do
      get 'new_lost'
      get 'new_found'
      get 'search'
      get 'recover'
      get 'autocomplete_tag_name'
      get 'tag'
      get 'recovered'
    end
  end
   
  get 'tags/:tag', :to => 'items#tag', :as => :tag 
  
  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
  match 'sobre' => 'contact#about', :as => 'about', :via => :get
end

ActionDispatch::Routing::Translator.translate_from_file(
  'config/locales/routes.yml', {
    prefix_on_default_locale: false,
    keep_untranslated_routes: true })
 

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <% if user_signed_in? %>
    <li>
			Bem vindo, <%=link_to current_user.name_with_message_count, user_path(current_user) %> 
			|
			<%= link_to 'Editar Conta', edit_user_registration_path%> |
    	<%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>   
		</li>
    
  <% else %>

	<div class="row">
		<%= form_for(:user, :as => :user, :url => session_path(:user)) do |f|%>
			<div class="one columns"> 
			</div>
		
			<div class="one columns" style="padding-right: 0px">
				<%= f.label :email%> 
			</div>
			<div class="two columns end" style="padding-left: 5px">
				<%= f.email_field :email, :style => "height: 20px; margin: 2px; padding:1px"%>
			</div>
		
			<div class="one columns" style="padding-right: 0px">
				<%= f.label :password, "Senha"%> 
			</div>
		
			<div class="two columns end" style="padding-left: 5px">
				<%= f.password_field :password, :style => "height: 20px; margin: 2px; padding:1px"%>
			</div>
		
			<div class="one column end">
				<%= f.submit "Entrar", :class => "small secondary button", :style => "padding: 2.5px 10px 2.5px 10px; margin-top: 2px" %>
			</div>
				<div class="two columns end" style ="padding:3px 0px 0px 0px ;text-align:left">
					Ainda não é cadastrado?
				</div>
				<div class="one column end" style="padding-bottom: 7px">
					<%= link_to 'Cadastrar', new_user_registration_path, :class => "small secondary button", :style => "padding: 4.0px 10px 4.0px 10px; margin-top: 2px" %>
				</div>
		<% end %>
	</div>
	<%end%>

</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ACHUSP</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="container" class="container">

      <header style="margin-bottom:10px">
					<div class="row" style="text-align: right">
        		<%= render 'layouts/navigation' %>
					</div>
				
				<div class="row" style="margin-bottom:10px">
					<div class="three columns" style="font-size:2.5em;">
						<a href="/achusp" class="logo">ACH<span style="font-weight:bold">USP</span></a>
					</div>
					<div class="nine columns">
					</div>
				</div>
			
      </header>
			<div class="row" style="position: relative">
				<div class="twelve columns" style="margin-bottom:20px;">
      		<%= render 'layouts/messages' %>
				</div>
			</div>
      <div id="main" role="main" class="row">
        <%= yield %>
      </div>
      <footer style="margin-top:10px; background-color:#666; height:50px; color:#EEE; padding: 15px; width:100%;position: absolute; bottom: 0px;">
	<div class="row">
			<div class="two columns" >
											<%= link_to(image_tag("botao_facebook.png", {:size => '32x32', :style => "margin-bottom: 0px; position:relative; bottom: 5px; left: 60px "}), "https://www.facebook.com/pages/Achusp/368103986620301", :style => "margin: 0px; padding:0px; font-size: 0px ")%>
			</div>
			<div class="four columns end">
	
				<%= link_to "Home", root_path%>
				<%=	link_to "Sobre o ACHUSP", about_path %>
				<%= link_to "Contato", contact_path%>
				
			</div>
			<div class="one column"></div>

			</div>
      </footer>
    </div> <!--! end of #container -->
  </body>
</html>